version: '3'

services:
  db:
    # Usamos la versión 7.0 que es muy estable
    image: mongo:7.0    
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DB}
    volumes:
      - ./mongo_data:/data/db
    restart: always
    #command: mongod --bind_ip_all --auth